apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-demo-helloworld
spec:
  selector:
    matchLabels:
      app: istio-demo-helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-demo-helloworld
    spec:
      containers:
      - name: istio-demo-helloworld
        image: istio-demo-helloworld:v0.1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: istio-demo-helloworld
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: istio-demo-helloworld
