apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-demo-helloworld 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-demo-helloworld
        version: v0.1
    spec:
      containers:
      - name: istio-demo-helloworld
        image: istio-demo-helloworld:v0.1
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: istio-demo-helloworld
  labels:
    app: istio-demo-helloworld
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 31380
  selector:
    app: istio-demo-helloworld
